---
volumes:
  hedgedoc-db-data: {}
  hedgedoc-data: {}
  openvscode-config: {}

networks:
  redkb-devnet: {}

services:
  mkdocs:
    container_name: redkb_mkdocs
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UV_BASE: ${UV_IMG_VERSION:-0.4.27}
        PYTHON_BASE: ${PYTHON_IMG_VERSION:-3.12-slim}
      ## Layer that runs mkdocs serve
      target: run
    volumes:
      - ./docs:/project/docs
      - ./includes:/project/includes
      - ./mkdocs.yml:/project/mkdocs.yml
    # expose:
    #   - 8000
    ports:
      - ${MKDOCS_HTTP_PORT:-8000}:8000
    networks:
      - redkb-devnet

  atheos:
    image: hlsiira/atheos
    container_name: redkb_atheos-ide
    restart: unless-stopped
    ports:
      - ${ATHEOS_WEBUI_PORT:-8080}:80
    volumes:
      - ./docs:/var/www/html/workspace/redkb:rw
    networks:
      - redkb-devnet

  openvscode-server:
    # image: lscr.io/linuxserver/openvscode-server:latest
    image: gitpod/openvscode-server
    container_name: openvscode-server
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CONNECTION_TOKEN= #optional
      - CONNECTION_SECRET= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
    volumes:
      - ~/.ssh:/home/openvscode-server/.ssh:ro
      - ${CODE_SERVER_CONF_DIR:-openvscode-config}:/config
      - ./:/home/workspace/redkb:cached
    ports:
      - 3000:3000
