site_name: RedKB
site_description: My personal knowledgebase
# site_url: https://github.com/redjax/red-utils

repo_name: redjax/redkb
repo_url: https://github.com/redjax/redkb

exclude_docs: |
  drafts/
  **/drafts/

use_directory_urls: false

theme:
  name: material
  highlightjs: true
  icon:
    repo: fontawesome/brands/git
  font:
    text: Open Sans

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: amber

  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - navigation.indexes
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  ## For better image support
  - glightbox
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: .
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  ## Enable markdown checklists, - [ ]/- [x]
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  ## Handle images
  - attr_list
  - md_in_html
  ## Render Markdown tables
  - tables
