site_name: RedKB
site_description: My personal knowledgebase
# site_url: https://github.com/redjax/red-utils

repo_name: redjax/redkb
repo_url: https://github.com/redjax/redkb

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/redjax
  ## True=show "Made with Material for MkDocs", false=hide
  generator: false

exclude_docs: |
  drafts/
  **/drafts/

use_directory_urls: false

theme:
  name: material
  highlightjs: true
  icon:
    repo: fontawesome/brands/git
  font:
    text: Open Sans

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: amber

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.code.select
    # - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.tabs
    - navigation.tracking
    # - navigation.sections
    - search.share
    - search.suggest
    - search.highlight
    - toc.follow

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  ## For better image support
  - glightbox
  - tags:
      tags_file: tags.md
      # tags_heirarchy: true  # Only available in "insiders" edition
  - git-revision-date-localized:
      ## Options: ["date", "datetime", "iso_date", "iso_datetime", "timeago"]
      type: timeago
      ## Show/hide creaetion date of file associated with page.
      #  Appears next to last updated date at bottom of page
      enable_creation_date: true
      ## Fallback to build date if mkdocs build is run outside of a git repo
      fallback_to_build_date: true
  ## Check rendered HTML for broken links, set ENABLED_HTMLPROOFEER=True to enable
  #  then run mkdocs serve command.
  - htmlproofer:
      enabled: !ENV [ENABLED_HTMLPROOFER, False]
      warn_on_ignored_urls: true
      validate_external_urls: True
      validate_rendered_template: True
  ## Enable offline version of site. Breaks many features.
  # - offline

markdown_extensions:
  ## Add footnotes to marked-up abbreviations to provide extra context.
  #  https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations
  - abbr
  - admonition
  - markdown_include.include:
      base_path: .
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      ## Add additional snippets, like *[Annotation]: ... glossaries
      auto_append:
        - includes/abbreviations.md
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  ## Enable markdown checklists, - [ ]/- [x]
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  ## Handle images
  - attr_list
  - md_in_html
  ## Render Markdown tables
  - tables

## Cookie consent banner
# extra:
#   consent:
#     title: Cookie consent
#     description: >- 
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of our documentation and whether users
#       find what they're searching for. With your consent, you're helping us to
#       make our documentation better.
