## Github Action to upgrade all packages with uv
name: Upgrade packages
on:
  ## Make this an on-demand Action
  workflow_dispatch:

jobs:
  bump-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Upgrade dependencies
        run: uv sync --upgrade --all-extras --dev

      - name: Create PR for dependency updates
        uses: peter-evans/create-pull-request@v5
        with:
          branch: chore/bump-depends
          commit-message: "chore: bump dependencies using uv"
          title: "Update packages"
          body: "Automated dependency version bumps via uv"
          base: main
