---
name: Build & Deploy MkDocs site
permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    branches:
      - main
    types: [ labeled ]


jobs:
  deploy-mkdocs:
    name: Deploy to Github Pages
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements/requirements.dev.txt
