name: Hugo CI and Deploy

on:
  pull_request:
    branches: [main]
    paths:
      - archetypes/**
      - content/**
      - data/**
      - i18n/**
      - static/**
      - hugo.yml
  push:
    branches: [main]
    paths:
      - archetypes/**
      - content/**
      - data/**
      - i18n/**
      - static/**
      - hugo.yml
  workflow_dispatch:
    inputs:
      deploy:
        description: Force deploy to Github Pages.
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.160.0
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25.6"

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Setup Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          if [[ -n "$DOMAIN_NAME" ]]; then
            BASE_URL="https://${DOMAIN_NAME}/"
          else
            BASE_URL="${{ steps.pages.outputs.base_url }}/"
          fi

          echo "Using baseURL: $BASE_URL"

          hugo \
            --gc --minify \
            --enableGitInfo \
            --baseURL "$BASE_URL"

      - name: Create CNAME file
        if: env.DOMAIN_NAME != ''
        run: |
          echo "$DOMAIN_NAME" > ./public/CNAME
          cat ./public/CNAME

      - name: Upload artifact
        if: github.event_name == 'push' || inputs.deploy == true
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./public

  deploy:
    if: github.event_name == 'push' || inputs.deploy == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
