---
name: Build & Deploy MkDocs site

on:
  pull_request:
    branches:
      - main
    types: [ labeled ]


jobs:
  deploy-mkdocs:
    name: Deploy to Github Pages
    if: ${{ github.event.label.name == 'publish' }}
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: 0.4.27

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build MkDocs site
        run: uv run mkdocs build

      - name: Deploy MkDocs to Github Pages
        run: uv run mkdocs gh-deploy

      # - name: Deploy MkDocs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     REQUIREMENTS: requirements/requirements.dev.txt
