---
name: Build & Deploy MkDocs site

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
  
    steps:
      - name: Deploy MkDocs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
