---
name: Hugo Site Main

on:
  push:
    branches:
      - main
    paths:
      - "apps/hugo-site/archetypes/**"
      - "apps/hugo-site/content/**"
      - "apps/hugo-site/data/**"
      - "apps/hugo-site/i18n/**"
      - "apps/hugo-site/static/**"
      - "apps/hugo-site/hugo.yml"
      - "apps/hugo-site/go.mod"
      - "apps/hugo-site/go.sum"

  workflow_dispatch:
    inputs:
      publish-gh-pages:
        type: boolean
        required: false
        default: false
      publish-to-branch:
        required: false
        default: false
        type: boolean
      branch-name:
        type: string
        required: false
        default: "gh-pages"
      publish-cf-pages:
        required: false
        default: false
        type: boolean
      runner-img-or-label:
        type: string
        default: ubuntu-latest

jobs:
  pipeline:
    permissions:
      contents: write
      actions: write
      pull-requests: write
      pages: write
      id-token: write
    uses: redjax/pipelinetemplates/.github/workflows/hugo-site-main.yml@topic/hugo-consolidated-pipelines
    # uses: redjax/pipelinetemplates/.github/workflows/hugo-site-main.yml@fix/hugo-pr-pipeline
    with:
      site-root: "apps/hugo-site"
      versioned: true
      version-file: ".version"
      artifact-name: "hugo-site"
      release-prefix: "site"
      branch-name: ${{ inputs.branch-name || 'gh-pages' }}
      publish-gh-pages: ${{ github.event_name == 'push' || inputs.publish-gh-pages || false }}
      publish-to-branch: ${{ inputs.publish-to-branch || false }}
      publish-cf-pages: ${{ github.event_name == 'push' || inputs.publish-cf-pages || false }}
      cloudflare-pages-project: "pipelinetemplates-test"
      cloudflare-pages-branch: "topic/hugo-consolidated-pipelines"
      # cloudflare-pages-branch: "fix/hugo-pr-pipeline"
      runner-image: ${{ inputs.runner-img-or-label || 'ubuntu-latest' }}
      templates-ref: topic/hugo-consolidated-pipelines
      # templates-ref: "fix/hugo-pr-pipeline"
    secrets:
      release-bot-pat: ${{ secrets.RELEASE_BOT_PAT }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
