---
name: Build Hugo site

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "apps/hugo-site/archetypes/**"
  #     - "apps/hugo-site/content/**"
  #     - "apps/hugo-site/data/**"
  #     - "apps/hugo-site/i18n/**"
  #     - "apps/hugo-site/static/**"
  #     - "apps/hugo-site/hugo.yml"
  #     - "apps/hugo-site/go.mod"
  #     - "apps/hugo-site/go.sum"

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "apps/hugo-site/archetypes/**"
      - "apps/hugo-site/content/**"
      - "apps/hugo-site/data/**"
      - "apps/hugo-site/i18n/**"
      - "apps/hugo-site/static/**"
      - "apps/hugo-site/hugo.yml"
      - "apps/hugo-site/go.mod"
      - "apps/hugo-site/go.sum"

  workflow_dispatch:
    inputs:
      runner-img-or-label:
        description: "A runner image (i.e. ubuntu-latest) or self-hosted runner label (i.e. pipelinetemplates-test)"
        required: true
        type: string
        default: ubuntu-latest

permissions:
  actions: write
  contents: write

jobs:
  build:
    uses: redjax/pipelinetemplates/.github/workflows/hugo-build.yml@topic/hugo-consolidated-pipelines
    with:
      site-root: "."
      artifact-name: "hugo-site"
      public-dir: "./public"
      build-flags: "--gc --minify --enableGitInfo"
      runner-image: ${{ inputs.runner-img-or-label || 'ubuntu-latest' }}
    secrets: inherit
