---
name: Hugo build

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Build Hugo site
        uses: redjax/pipelinetemplates/.github/actions/hugo-build@gh/hugo-build/v0.0.3
        with:
          source-dir: "."
          public-dir: "public"
          check-changed: "false"
          use-cache: "true"
          environment: "production"
          build-flags: "--gc --minify --enableGitInfo"
          publish-artifact: "true"
          artifact-name: "hugo-site"
          artifact-if-no-files-found: "error"
          artifact-retention-days: "7"
